begin;

create table if not exists app_plant_species (
    id integer generated by default as identity primary key,
    plant_type_id integer not null references app_plant_types(id) on delete restrict,
    name varchar(120) not null,
    latin_name varchar(160) not null default '',
    care_description text not null default '',
    unique (plant_type_id, name)
);

alter table app_plants add column if not exists plant_type_id integer references app_plant_types(id);
alter table app_plants add column if not exists species_id integer references app_plant_species(id) on delete set null;
alter table app_plants add column if not exists lifecycle_phase varchar(80) not null default 'Активный рост';
alter table app_plants add column if not exists health_status varchar(80) not null default 'Здорово';
alter table app_plants add column if not exists location varchar(160) not null default '';
alter table app_plants add column if not exists notes text not null default '';

alter table app_watering_schedules add column if not exists period_value integer not null default 1;
alter table app_watering_schedules add column if not exists period_unit_id integer references app_period_units(id);
alter table app_watering_schedules add column if not exists last_completed_date date;
alter table app_watering_schedules drop constraint if exists app_watering_schedules_type_check;
alter table app_watering_schedules add constraint app_watering_schedules_type_check
    check (type in ('Watering', 'Fertilizer', 'Pruning', 'Repotting'));

alter table app_photos add column if not exists title varchar(160) not null default '';

create table if not exists app_care_events (
    id integer generated by default as identity primary key,
    schedule_id integer not null references app_watering_schedules(id) on delete cascade,
    plant_id integer not null references app_plants(id) on delete cascade,
    scheduled_date date not null,
    completed_at timestamp,
    status varchar(20) not null default 'Planned'
        check (status in ('Planned', 'Done', 'Skipped')),
    note text not null default '',
    unique (schedule_id, scheduled_date)
);

create table if not exists app_issue_observations (
    id integer generated by default as identity primary key,
    plant_id integer not null references app_plants(id) on delete cascade,
    reference_item_id integer not null references app_reference_items(id) on delete cascade,
    observed_at date not null,
    note text not null default ''
);

create table if not exists app_recommendation_settings (
    code varchar(60) primary key,
    numeric_value numeric(10,2) not null,
    description varchar(240) not null
);

create table if not exists app_protection_products (
    id integer generated by default as identity primary key,
    name varchar(160) not null unique,
    active_ingredient varchar(200) not null default '',
    application_description text not null,
    hazard_class varchar(80) not null default ''
);

alter table app_plants drop constraint if exists app_plants_user_id_fkey;
alter table app_plants add constraint app_plants_user_id_fkey
    foreign key (user_id) references app_users(id) on delete cascade;

alter table app_watering_schedules drop constraint if exists app_watering_schedules_plant_id_fkey;
alter table app_watering_schedules add constraint app_watering_schedules_plant_id_fkey
    foreign key (plant_id) references app_plants(id) on delete cascade;

alter table app_photos drop constraint if exists app_photos_plant_id_fkey;
alter table app_photos add constraint app_photos_plant_id_fkey
    foreign key (plant_id) references app_plants(id) on delete cascade;

update app_plants p
set plant_type_id = t.id
from app_plant_types t
where p.plant_type_id is null and p.type = t.name;

update app_watering_schedules
set period_value = period_days,
    period_unit_id = (select id from app_period_units where code = 'day')
where period_unit_id is null;

insert into app_recommendation_settings (code, numeric_value, description)
values
    ('photo_check_days', 14, 'Через сколько дней рекомендовать новое фото'),
    ('repot_check_days', 365, 'Через сколько дней проверять необходимость пересадки'),
    ('pruning_check_days', 90, 'Через сколько дней напоминать об осмотре для обрезки')
on conflict (code) do nothing;

insert into app_protection_products (name, active_ingredient, application_description, hazard_class)
values
    ('Зелёное мыло', 'Калийные соли жирных кислот', 'Использовать для промывания листьев при небольшом количестве сосущих вредителей.', 'Низкая'),
    ('Биологический инсектицид', 'Аверсектин C', 'Применять строго по инструкции производителя с повторной обработкой при необходимости.', 'Средняя'),
    ('Биологический фунгицид', 'Bacillus subtilis', 'Использовать для профилактики и при первых признаках грибковых заболеваний.', 'Низкая')
on conflict (name) do nothing;

do $$
begin
    if to_regclass('public.app_pests') is not null then
        insert into app_reference_items (category_id, name, treatment_description, image_path)
        select c.id, p.name, p.treatment_description, p.image_path
        from app_pests p
        join app_reference_categories c on c.code = case when p.is_pest then 'pest' else 'disease' end
        on conflict (category_id, name) do nothing;
    end if;

    if to_regclass('public.app_diseases') is not null then
        insert into app_reference_items (category_id, name, treatment_description, image_path)
        select c.id, d.name, d.treatment_description, d.image_path
        from app_diseases d
        join app_reference_categories c on c.code = 'disease'
        on conflict (category_id, name) do nothing;
    end if;
end $$;

drop table if exists app_diseases;
drop table if exists app_pests;

commit;
