create table if not exists plants (
    id integer generated by default as identity primary key,
    name varchar(120) not null,
    latin_name varchar(160),
    type varchar(80),
    location varchar(160),
    last_watered date,
    watering_hint text,
    health_status varchar(80),
    notes text,
    accent_color varchar(16) default '#6DD6A3'
);

create table if not exists plant_photos (
    id integer generated by default as identity primary key,
    plant_id integer not null references plants(id) on delete cascade,
    caption varchar(180) not null,
    taken_at date not null default current_date,
    placeholder_color varchar(16) default '#2F4858'
);

create table if not exists care_tasks (
    id integer generated by default as identity primary key,
    plant_id integer not null references plants(id) on delete cascade,
    title varchar(160) not null,
    description text,
    due_date date not null,
    status varchar(30) not null default 'Planned'
);

create table if not exists pest_issues (
    id integer generated by default as identity primary key,
    name varchar(120) not null,
    issue_type varchar(30) not null,
    severity varchar(80),
    symptoms text,
    treatment text,
    prevention text,
    accent_color varchar(16) default '#F4B860',
    constraint ck_pest_issues_type check (issue_type in ('Pest', 'Disease'))
);

insert into plants (name, latin_name, type, location, last_watered, watering_hint, health_status, notes, accent_color)
values
    ('Монстера', 'Monstera deliciosa', 'Декоративно-лиственное', 'Гостиная', current_date - 2, 'Проверить верхние 3 см грунта', 'Здоровое', 'Любит опору и протирание листьев.', '#6DD6A3'),
    ('Фикус', 'Ficus elastica', 'Декоративно-лиственное', 'Кабинет', current_date - 5, 'Полив после просушки', 'Нужен осмотр', 'Не любит сквозняки.', '#8BC34A'),
    ('Кактус', 'Mammillaria', 'Суккулент', 'Кухня', current_date - 18, 'Редкий полив', 'Здоровое', 'Зимой держать почти сухим.', '#A5D6A7')
on conflict do nothing;

insert into plant_photos (plant_id, caption, taken_at, placeholder_color)
select p.id, 'Первое наблюдение', current_date - 3, p.accent_color
from plants p
where p.name in ('Монстера', 'Фикус', 'Кактус')
  and not exists (select 1 from plant_photos pp where pp.plant_id = p.id);

insert into care_tasks (plant_id, title, description, due_date, status)
select p.id, 'Проверить влажность грунта', 'Задача ухода для главной коллекции.', current_date, 'Planned'
from plants p
where p.name = 'Монстера'
  and not exists (select 1 from care_tasks ct where ct.plant_id = p.id and ct.title = 'Проверить влажность грунта');

insert into pest_issues (name, issue_type, severity, symptoms, treatment, prevention, accent_color)
values
    ('Тля', 'Pest', 'Средний риск', 'Колонии мелких насекомых на молодых побегах.', 'Смыть теплым душем и обработать мыльным раствором.', 'Карантин новых растений.', '#F4B860'),
    ('Паутинный клещ', 'Pest', 'Высокий риск', 'Тонкая паутинка и светлые точки на листьях.', 'Изолировать растение и применить акарицид.', 'Поддерживать влажность воздуха.', '#FF9F80'),
    ('Щитовка', 'Pest', 'Высокий риск', 'Коричневые бляшки на листьях и стеблях.', 'Снять вручную и обработать инсектицидом.', 'Регулярный осмотр листьев.', '#D98E73'),
    ('Мучнистая роса', 'Disease', 'Средний риск', 'Белый мучнистый налет на листьях.', 'Удалить пораженные части и применить фунгицид.', 'Проветривание и умеренная влажность.', '#BFD7EA'),
    ('Корневая гниль', 'Disease', 'Критический риск', 'Вялость при влажном грунте и темные корни.', 'Удалить поврежденные корни и пересадить.', 'Дренаж и полив после просушки.', '#9B5DE5')
on conflict do nothing;
