-- Физическая модель Plants для PostgreSQL.
-- Таблицы разделены по предметным сущностям и соответствуют третьей нормальной форме.

create table if not exists app_users (
    id integer generated by default as identity primary key,
    google_id varchar(200) not null unique,
    name varchar(160) not null,
    email varchar(200) not null,
    avatar_url text not null default '',
    is_admin boolean not null default false
);

create unique index if not exists app_users_single_admin_idx
    on app_users ((is_admin))
    where is_admin = true;

create table if not exists app_plant_types (
    id integer generated by default as identity primary key,
    name varchar(40) not null unique
);

create table if not exists app_plant_species (
    id integer generated by default as identity primary key,
    plant_type_id integer not null references app_plant_types(id) on delete restrict,
    name varchar(120) not null,
    latin_name varchar(160) not null default '',
    care_description text not null default '',
    unique (plant_type_id, name)
);

create table if not exists app_period_units (
    id integer generated by default as identity primary key,
    code varchar(20) not null unique,
    name varchar(40) not null unique,
    day_multiplier integer not null check (day_multiplier > 0)
);

create table if not exists app_plants (
    id integer generated by default as identity primary key,
    user_id integer not null references app_users(id) on delete cascade,
    plant_type_id integer references app_plant_types(id) on delete restrict,
    species_id integer references app_plant_species(id) on delete set null,
    name varchar(120) not null,
    type varchar(40) not null,
    watering_enabled boolean not null default false,
    fertilizer_enabled boolean not null default false,
    lifecycle_phase varchar(80) not null default 'Активный рост',
    health_status varchar(80) not null default 'Здорово',
    location varchar(160) not null default '',
    notes text not null default ''
);

create table if not exists app_watering_schedules (
    id integer generated by default as identity primary key,
    plant_id integer not null references app_plants(id) on delete cascade,
    period_unit_id integer references app_period_units(id) on delete restrict,
    start_date date not null,
    period_days integer not null check (period_days > 0),
    period_value integer not null check (period_value > 0),
    notification_time time not null,
    type varchar(20) not null
        check (type in ('Watering', 'Fertilizer', 'Pruning', 'Repotting')),
    last_completed_date date
);

create table if not exists app_care_events (
    id integer generated by default as identity primary key,
    schedule_id integer not null references app_watering_schedules(id) on delete cascade,
    plant_id integer not null references app_plants(id) on delete cascade,
    scheduled_date date not null,
    completed_at timestamp,
    status varchar(20) not null default 'Planned'
        check (status in ('Planned', 'Done', 'Skipped')),
    note text not null default '',
    unique (schedule_id, scheduled_date)
);

create table if not exists app_photos (
    id integer generated by default as identity primary key,
    plant_id integer not null references app_plants(id) on delete cascade,
    title varchar(160) not null,
    file_path text not null,
    date_taken timestamp not null
);

create table if not exists app_reference_categories (
    id integer generated by default as identity primary key,
    code varchar(20) not null unique,
    name varchar(80) not null unique
);

create table if not exists app_reference_items (
    id integer generated by default as identity primary key,
    category_id integer not null references app_reference_categories(id) on delete cascade,
    name varchar(160) not null,
    treatment_description text not null,
    image_path text not null default '',
    unique (category_id, name)
);

create table if not exists app_reference_item_plant_types (
    reference_item_id integer not null references app_reference_items(id) on delete cascade,
    plant_type_id integer not null references app_plant_types(id) on delete cascade,
    primary key (reference_item_id, plant_type_id)
);

create table if not exists app_issue_observations (
    id integer generated by default as identity primary key,
    plant_id integer not null references app_plants(id) on delete cascade,
    reference_item_id integer not null references app_reference_items(id) on delete cascade,
    observed_at date not null,
    note text not null default ''
);

create table if not exists app_recommendation_settings (
    code varchar(60) primary key,
    numeric_value numeric(10,2) not null,
    description varchar(240) not null
);

create table if not exists app_protection_products (
    id integer generated by default as identity primary key,
    name varchar(160) not null unique,
    active_ingredient varchar(200) not null default '',
    application_description text not null,
    hazard_class varchar(80) not null default ''
);

insert into app_plant_types (name)
values ('Лиственные'), ('Цветущие'), ('Суккуленты')
on conflict (name) do nothing;

insert into app_period_units (code, name, day_multiplier)
values ('day', 'день', 1), ('week', 'неделя', 7), ('month', 'месяц', 30)
on conflict (code) do nothing;

insert into app_reference_categories (code, name)
values ('pest', 'Вредители'), ('disease', 'Болезни')
on conflict (code) do nothing;

insert into app_plant_species (plant_type_id, name, latin_name, care_description)
select id, 'Монстера', 'Monstera deliciosa',
       'Рассеянный свет и умеренный полив после подсыхания верхнего слоя грунта.'
from app_plant_types where name = 'Лиственные'
on conflict (plant_type_id, name) do nothing;

insert into app_plant_species (plant_type_id, name, latin_name, care_description)
select id, 'Фикус', 'Ficus elastica',
       'Яркий рассеянный свет, защита от сквозняков и умеренный полив.'
from app_plant_types where name = 'Лиственные'
on conflict (plant_type_id, name) do nothing;

insert into app_plant_species (plant_type_id, name, latin_name, care_description)
select id, 'Герань', 'Pelargonium',
       'Солнечное место и регулярное удаление увядших цветков.'
from app_plant_types where name = 'Цветущие'
on conflict (plant_type_id, name) do nothing;

insert into app_plant_species (plant_type_id, name, latin_name, care_description)
select id, 'Кактус', 'Cactaceae',
       'Яркий свет и редкий полив после полного просыхания грунта.'
from app_plant_types where name = 'Суккуленты'
on conflict (plant_type_id, name) do nothing;

insert into app_recommendation_settings (code, numeric_value, description)
values
    ('photo_check_days', 14, 'Через сколько дней рекомендовать новое фото'),
    ('repot_check_days', 365, 'Через сколько дней проверять необходимость пересадки'),
    ('pruning_check_days', 90, 'Через сколько дней напоминать об осмотре для обрезки')
on conflict (code) do nothing;

insert into app_protection_products (name, active_ingredient, application_description, hazard_class)
values
    ('Зелёное мыло', 'Калийные соли жирных кислот', 'Использовать для промывания листьев при небольшом количестве сосущих вредителей.', 'Низкая'),
    ('Биологический инсектицид', 'Аверсектин C', 'Применять строго по инструкции производителя с повторной обработкой при необходимости.', 'Средняя'),
    ('Биологический фунгицид', 'Bacillus subtilis', 'Использовать для профилактики и при первых признаках грибковых заболеваний.', 'Низкая')
on conflict (name) do nothing;

insert into app_reference_items (category_id, name, treatment_description, image_path)
select c.id, v.name, v.treatment, v.image_path
from app_reference_categories c
join (values
    ('pest', 'Тля', 'Колонии на молодых побегах. Промыть растение и применить инсектицид.', 'resource://issue_aphids'),
    ('pest', 'Паутинный клещ', 'Светлые точки и паутинка. Промыть растение и применить акарицид.', 'resource://issue_spider_mite'),
    ('pest', 'Щитовка', 'Коричневые бляшки. Удалить вручную и применить системный инсектицид.', 'resource://issue_scale'),
    ('pest', 'Мучнистый червец', 'Белые ватные колонии. Удалить вручную и провести повторные обработки.', 'resource://issue_mealybug'),
    ('pest', 'Трипсы', 'Серебристые повреждения. Удалить поражённые части и применить инсектицид.', 'resource://issue_thrips'),
    ('pest', 'Грибные комарики', 'Мушки у влажного грунта. Просушить субстрат и уничтожить личинок.', 'resource://issue_fungus_gnat'),
    ('disease', 'Мучнистая роса', 'Белый налёт. Удалить поражённые листья и применить фунгицид.', 'resource://issue_powdery_mildew'),
    ('disease', 'Корневая гниль', 'Удалить гнилые корни, заменить грунт и сократить полив.', 'resource://issue_root_rot'),
    ('disease', 'Пятнистость листьев', 'Удалить поражённые листья и применить фунгицид.', 'resource://issue_leaf_spot'),
    ('disease', 'Серая гниль', 'Удалить заражённые части, уменьшить влажность и применить фунгицид.', 'resource://issue_gray_mold'),
    ('disease', 'Ржавчина растений', 'Удалить поражённые листья и применить системный фунгицид.', 'resource://issue_rust'),
    ('disease', 'Сажистый грибок', 'Уничтожить сосущих вредителей и промыть листья.', 'resource://issue_sooty_mold'),
    ('disease', 'Бактериальная мягкая гниль', 'Удалить поражённую ткань, обработать срез и сократить полив.', 'resource://issue_soft_rot'),
    ('disease', 'Пробковая пятнистость кактусов', 'Исправить условия содержания и при распространении применить фунгицид.', 'resource://issue_cactus_scab'),
    ('disease', 'Эдема листьев', 'Сократить полив, увеличить освещение и вентиляцию.', 'resource://issue_edema'),
    ('disease', 'Хлороз', 'Проверить грунт и корни, внести удобрение с микроэлементами.', 'resource://issue_chlorosis')
) as v(category_code, name, treatment, image_path) on v.category_code = c.code
on conflict (category_id, name) do update
set treatment_description = excluded.treatment_description,
    image_path = excluded.image_path;

insert into app_reference_item_plant_types (reference_item_id, plant_type_id)
select i.id, t.id
from app_reference_items i
join app_reference_categories c on c.id = i.category_id
cross join app_plant_types t
where
    (i.name in ('Паутинный клещ', 'Мучнистый червец', 'Грибные комарики', 'Корневая гниль', 'Хлороз')) or
    (i.name in ('Тля', 'Трипсы', 'Мучнистая роса', 'Пятнистость листьев', 'Серая гниль',
                'Ржавчина растений', 'Сажистый грибок', 'Эдема листьев')
        and t.name in ('Лиственные', 'Цветущие')) or
    (i.name = 'Щитовка' and t.name in ('Лиственные', 'Суккуленты')) or
    (i.name = 'Бактериальная мягкая гниль' and t.name in ('Цветущие', 'Суккуленты')) or
    (i.name = 'Пробковая пятнистость кактусов' and t.name = 'Суккуленты')
on conflict do nothing;
