using Npgsql;
using Plants.Models;

namespace Plants.Services.Database;

public sealed class ServerDatabaseService
{
    private bool _initialized;
    private const string PlantSelectSql = """
        select p.id, p.user_id, p.name, p.type, p.watering_enabled, p.fertilizer_enabled,
               p.species_id, coalesce(s.latin_name, ''), p.lifecycle_phase,
               p.health_status, p.location, p.notes
        from app_plants p
        left join app_plant_species s on s.id = p.species_id
        """;

    public async Task InitializeAsync()
    {
        if (_initialized)
        {
            return;
        }

        await using var connection = await OpenAsync();
        await using var command = connection.CreateCommand();
        command.CommandText = """
            create table if not exists app_users (
                id integer generated by default as identity primary key,
                google_id varchar(200) not null unique,
                name varchar(160) not null,
                email varchar(200) not null,
                avatar_url text not null default '',
                is_admin boolean not null default false
            );

            with ranked_admins as (
                select id, row_number() over (order by id) as rn
                from app_users
                where is_admin = true
            )
            update app_users u
            set is_admin = false
            from ranked_admins r
            where u.id = r.id and r.rn > 1;

            create unique index if not exists app_users_single_admin_idx
            on app_users ((is_admin))
            where is_admin = true;

            do $$
            begin
                if to_regclass('public.app_plants') is not null then
                    alter table app_plants drop constraint if exists app_plants_user_id_fkey;
                    alter table app_plants
                        add constraint app_plants_user_id_fkey
                        foreign key (user_id) references app_users(id) on delete cascade;
                end if;

                if to_regclass('public.app_watering_schedules') is not null
                   and to_regclass('public.app_plants') is not null then
                    alter table app_watering_schedules drop constraint if exists app_watering_schedules_plant_id_fkey;
                    alter table app_watering_schedules
                        add constraint app_watering_schedules_plant_id_fkey
                        foreign key (plant_id) references app_plants(id) on delete cascade;
                end if;

                if to_regclass('public.app_photos') is not null
                   and to_regclass('public.app_plants') is not null then
                    alter table app_photos drop constraint if exists app_photos_plant_id_fkey;
                    alter table app_photos
                        add constraint app_photos_plant_id_fkey
                        foreign key (plant_id) references app_plants(id) on delete cascade;
                end if;

                if to_regclass('public.app_reference_items') is not null
                   and to_regclass('public.app_reference_categories') is not null then
                    alter table app_reference_items drop constraint if exists app_reference_items_category_id_fkey;
                    alter table app_reference_items
                        add constraint app_reference_items_category_id_fkey
                        foreign key (category_id) references app_reference_categories(id) on delete cascade;
                end if;
            end $$;

            create table if not exists app_plant_types (
                id integer generated by default as identity primary key,
                name varchar(40) not null unique
            );

            create table if not exists app_plant_species (
                id integer generated by default as identity primary key,
                plant_type_id integer not null references app_plant_types(id) on delete restrict,
                name varchar(120) not null,
                latin_name varchar(160) not null default '',
                care_description text not null default '',
                unique (plant_type_id, name)
            );

            create table if not exists app_period_units (
                id integer generated by default as identity primary key,
                code varchar(20) not null unique,
                name varchar(40) not null unique,
                day_multiplier integer not null check (day_multiplier > 0)
            );

            create table if not exists app_plants (
                id integer generated by default as identity primary key,
                user_id integer not null references app_users(id) on delete cascade,
                name varchar(120) not null,
                type varchar(40) not null,
                plant_type_id integer references app_plant_types(id),
                species_id integer references app_plant_species(id) on delete set null,
                watering_enabled boolean not null default false,
                fertilizer_enabled boolean not null default false,
                lifecycle_phase varchar(80) not null default 'Активный рост',
                health_status varchar(80) not null default 'Здорово',
                location varchar(160) not null default '',
                notes text not null default ''
            );

            create table if not exists app_watering_schedules (
                id integer generated by default as identity primary key,
                plant_id integer not null references app_plants(id) on delete cascade,
                start_date date not null,
                period_days integer not null check (period_days > 0),
                period_value integer not null default 1 check (period_value > 0),
                period_unit_id integer references app_period_units(id),
                notification_time time not null,
                type varchar(20) not null check (type in ('Watering', 'Fertilizer', 'Pruning', 'Repotting')),
                last_completed_date date
            );

            alter table app_watering_schedules
                add column if not exists last_completed_date date;

            alter table app_watering_schedules
                add column if not exists period_value integer not null default 1;

            alter table app_watering_schedules
                add column if not exists period_unit_id integer references app_period_units(id);

            alter table app_watering_schedules
                drop constraint if exists app_watering_schedules_type_check;

            alter table app_watering_schedules
                add constraint app_watering_schedules_type_check
                check (type in ('Watering', 'Fertilizer', 'Pruning', 'Repotting'));

            alter table app_plants
                add column if not exists plant_type_id integer references app_plant_types(id);

            alter table app_plants
                add column if not exists species_id integer references app_plant_species(id) on delete set null;

            alter table app_plants
                add column if not exists lifecycle_phase varchar(80) not null default 'Активный рост';

            alter table app_plants
                add column if not exists health_status varchar(80) not null default 'Здорово';

            alter table app_plants
                add column if not exists location varchar(160) not null default '';

            alter table app_plants
                add column if not exists notes text not null default '';

            create table if not exists app_photos (
                id integer generated by default as identity primary key,
                plant_id integer not null references app_plants(id) on delete cascade,
                title varchar(160) not null default '',
                file_path text not null,
                date_taken timestamp not null
            );

            alter table app_photos
                add column if not exists title varchar(160) not null default '';

            create table if not exists app_reference_categories (
                id integer generated by default as identity primary key,
                code varchar(20) not null unique,
                name varchar(80) not null unique
            );

            create table if not exists app_reference_items (
                id integer generated by default as identity primary key,
                category_id integer not null references app_reference_categories(id),
                name varchar(160) not null,
                treatment_description text not null,
                image_path text not null default '',
                unique (category_id, name)
            );

            create table if not exists app_reference_item_plant_types (
                reference_item_id integer not null references app_reference_items(id) on delete cascade,
                plant_type_id integer not null references app_plant_types(id) on delete cascade,
                primary key (reference_item_id, plant_type_id)
            );

            create table if not exists app_care_events (
                id integer generated by default as identity primary key,
                schedule_id integer not null references app_watering_schedules(id) on delete cascade,
                plant_id integer not null references app_plants(id) on delete cascade,
                scheduled_date date not null,
                completed_at timestamp,
                status varchar(20) not null default 'Planned'
                    check (status in ('Planned', 'Done', 'Skipped')),
                note text not null default '',
                unique (schedule_id, scheduled_date)
            );

            create table if not exists app_issue_observations (
                id integer generated by default as identity primary key,
                plant_id integer not null references app_plants(id) on delete cascade,
                reference_item_id integer not null references app_reference_items(id) on delete cascade,
                observed_at date not null,
                note text not null default ''
            );

            create table if not exists app_recommendation_settings (
                code varchar(60) primary key,
                numeric_value numeric(10,2) not null,
                description varchar(240) not null
            );

            create table if not exists app_protection_products (
                id integer generated by default as identity primary key,
                name varchar(160) not null unique,
                active_ingredient varchar(200) not null default '',
                application_description text not null,
                hazard_class varchar(80) not null default ''
            );

            alter table app_plants
                drop constraint if exists app_plants_user_id_fkey;
            alter table app_plants
                add constraint app_plants_user_id_fkey
                foreign key (user_id) references app_users(id) on delete cascade;

            alter table app_watering_schedules
                drop constraint if exists app_watering_schedules_plant_id_fkey;
            alter table app_watering_schedules
                add constraint app_watering_schedules_plant_id_fkey
                foreign key (plant_id) references app_plants(id) on delete cascade;

            alter table app_photos
                drop constraint if exists app_photos_plant_id_fkey;
            alter table app_photos
                add constraint app_photos_plant_id_fkey
                foreign key (plant_id) references app_plants(id) on delete cascade;

            alter table app_reference_items
                drop constraint if exists app_reference_items_category_id_fkey;
            alter table app_reference_items
                add constraint app_reference_items_category_id_fkey
                foreign key (category_id) references app_reference_categories(id) on delete cascade;

            insert into app_plant_types (name)
            values ('Лиственные'), ('Цветущие'), ('Суккуленты')
            on conflict (name) do nothing;

            insert into app_plant_species (plant_type_id, name, latin_name, care_description)
            select id, 'Монстера', 'Monstera deliciosa', 'Рассеянный свет, умеренный полив после подсыхания верхнего слоя грунта.'
            from app_plant_types where name='Лиственные'
            on conflict (plant_type_id, name) do nothing;

            insert into app_plant_species (plant_type_id, name, latin_name, care_description)
            select id, 'Фикус', 'Ficus elastica', 'Яркий рассеянный свет, защита от сквозняков и умеренный полив.'
            from app_plant_types where name='Лиственные'
            on conflict (plant_type_id, name) do nothing;

            insert into app_plant_species (plant_type_id, name, latin_name, care_description)
            select id, 'Герань', 'Pelargonium', 'Солнечное место, регулярное удаление увядших цветков.'
            from app_plant_types where name='Цветущие'
            on conflict (plant_type_id, name) do nothing;

            insert into app_plant_species (plant_type_id, name, latin_name, care_description)
            select id, 'Кактус', 'Cactaceae', 'Яркий свет и редкий полив после полного просыхания грунта.'
            from app_plant_types where name='Суккуленты'
            on conflict (plant_type_id, name) do nothing;

            insert into app_recommendation_settings (code, numeric_value, description)
            values
                ('photo_check_days', 14, 'Через сколько дней рекомендовать новое фото'),
                ('repot_check_days', 365, 'Через сколько дней напоминать о проверке необходимости пересадки'),
                ('pruning_check_days', 90, 'Через сколько дней напоминать об осмотре для обрезки')
            on conflict (code) do nothing;

            insert into app_protection_products (name, active_ingredient, application_description, hazard_class)
            values
                ('Зелёное мыло', 'Калийные соли жирных кислот', 'Использовать для промывания листьев при небольшом количестве сосущих вредителей.', 'Низкая'),
                ('Биологический инсектицид', 'Аверсектин C', 'Применять строго по инструкции производителя с повторной обработкой при необходимости.', 'Средняя'),
                ('Биологический фунгицид', 'Bacillus subtilis', 'Использовать для профилактики и при первых признаках грибковых заболеваний.', 'Низкая')
            on conflict (name) do nothing;

            insert into app_period_units (code, name, day_multiplier)
            values ('day', 'день', 1), ('week', 'неделя', 7), ('month', 'месяц', 30)
            on conflict (code) do nothing;

            insert into app_reference_categories (code, name)
            values ('pest', 'Вредители'), ('disease', 'Болезни')
            on conflict (code) do nothing;

            update app_plants p
            set plant_type_id = t.id
            from app_plant_types t
            where p.plant_type_id is null and p.type = t.name;

            update app_watering_schedules
            set period_value = period_days,
                period_unit_id = (select id from app_period_units where code = 'day')
            where period_unit_id is null;

            do $$
            begin
                if to_regclass('public.app_pests') is not null then
                    insert into app_reference_items (category_id, name, treatment_description, image_path)
                    select c.id, p.name, p.treatment_description, p.image_path
                    from app_pests p
                    join app_reference_categories c on c.code = case when p.is_pest then 'pest' else 'disease' end
                    on conflict (category_id, name) do nothing;
                end if;

                if to_regclass('public.app_diseases') is not null then
                    insert into app_reference_items (category_id, name, treatment_description, image_path)
                    select c.id, d.name, d.treatment_description, d.image_path
                    from app_diseases d
                    join app_reference_categories c on c.code = 'disease'
                    on conflict (category_id, name) do nothing;
                end if;
            end $$;

            insert into app_reference_items (category_id, name, treatment_description, image_path)
            select c.id, v.name, v.treatment, v.image_path
            from app_reference_categories c
            join (values
                ('pest', 'Тля', E'Признаки: колонии зелёных или чёрных насекомых на молодых побегах, липкий налёт, скрученные листья.\n\nЛечение: изолируйте растение, промойте листья мыльным раствором и обработайте инсектицидом. Повторите обработку через 7–10 дней.\n\nПрофилактика: осматривайте новые растения и не перекармливайте азотными удобрениями.', 'resource://issue_aphids'),
                ('pest', 'Паутинный клещ', E'Признаки: мелкие светлые точки, сухие листья и тонкая паутинка с обратной стороны листа.\n\nЛечение: изолируйте растение, тщательно промойте крону и примените акарицид 2–3 раза с интервалом по инструкции.\n\nПрофилактика: поддерживайте подходящую влажность воздуха и регулярно осматривайте листья.', 'resource://issue_spider_mite'),
                ('pest', 'Щитовка', E'Признаки: неподвижные коричневые бляшки на листьях и стеблях, липкие выделения, замедление роста.\n\nЛечение: снимите вредителей ватной палочкой, промойте растение и примените системный инсектицид.\n\nПрофилактика: протирайте листья и выдерживайте новые растения в карантине.', 'resource://issue_scale'),
                ('pest', 'Мучнистый червец', E'Признаки: белые ватные комочки в пазухах листьев и на корнях, липкий налёт, деформация побегов.\n\nЛечение: удалите колонии вручную и проведите несколько обработок системным инсектицидом.\n\nПрофилактика: не допускайте тесного размещения растений и регулярно проверяйте пазухи листьев.', 'resource://issue_mealybug'),
                ('pest', 'Трипсы', E'Признаки: серебристые штрихи и пятна, чёрные точки экскрементов, деформированные бутоны.\n\nЛечение: удалите сильно повреждённые части, установите клеевые ловушки и обработайте растение инсектицидом.\n\nПрофилактика: карантин новых растений и регулярный осмотр цветков и молодых листьев.', 'resource://issue_thrips'),
                ('pest', 'Грибные комарики', E'Признаки: мелкие тёмные мушки возле влажного грунта, личинки в субстрате, ослабление молодых корней.\n\nЛечение: просушите верхний слой грунта, замените его и примените средство против почвенных личинок.\n\nПрофилактика: избегайте постоянного переувлажнения и используйте чистый рыхлый субстрат.', 'resource://issue_fungus_gnat'),
                ('disease', 'Мучнистая роса', E'Признаки: белый мучнистый налёт, который постепенно покрывает листья и побеги.\n\nЛечение: удалите поражённые части, улучшите проветривание и обработайте фунгицидом.\n\nПрофилактика: не загущайте крону, избегайте резких перепадов температуры и сырости.', 'resource://issue_powdery_mildew'),
                ('disease', 'Корневая гниль', E'Признаки: вялость при влажном грунте, неприятный запах, потемневшие мягкие корни.\n\nЛечение: выньте растение из горшка, удалите гнилые корни, обработайте срезы и пересадите в свежий грунт.\n\nПрофилактика: используйте дренаж и поливайте только после необходимой просушки.', 'resource://issue_root_rot'),
                ('disease', 'Пятнистость листьев', E'Признаки: округлые коричневые или чёрные пятна с жёлтой каймой, постепенное отмирание ткани.\n\nЛечение: удалите поражённые листья, прекратите опрыскивание кроны и примените фунгицид.\n\nПрофилактика: поливайте под корень и обеспечивайте циркуляцию воздуха.', 'resource://issue_leaf_spot'),
                ('disease', 'Серая гниль', E'Признаки: серый пушистый налёт на цветках и листьях, водянистые бурые участки.\n\nЛечение: удалите заражённые части, уменьшите влажность и обработайте фунгицидом против ботритиса.\n\nПрофилактика: проветривайте помещение и не оставляйте воду на цветках.', 'resource://issue_gray_mold'),
                ('disease', 'Ржавчина растений', E'Признаки: оранжевые или бурые порошащие подушечки с обратной стороны листьев.\n\nЛечение: удалите поражённые листья и проведите обработку системным фунгицидом.\n\nПрофилактика: не переувлажняйте листья и не ставьте растения слишком тесно.', 'resource://issue_rust'),
                ('disease', 'Сажистый грибок', E'Признаки: чёрный налёт, похожий на сажу, поверх липких выделений вредителей.\n\nЛечение: сначала уничтожьте тлю, щитовку или червеца, затем аккуратно промойте листья.\n\nПрофилактика: своевременно контролируйте сосущих вредителей.', 'resource://issue_sooty_mold'),
                ('disease', 'Бактериальная мягкая гниль', E'Признаки: быстро увеличивающиеся мягкие водянистые участки и неприятный запах.\n\nЛечение: немедленно удалите поражённую ткань стерильным инструментом, обработайте срез и сократите полив.\n\nПрофилактика: дезинфицируйте инструменты и не допускайте застоя воды.', 'resource://issue_soft_rot'),
                ('disease', 'Пробковая пятнистость кактусов', E'Признаки: сухие коричневые пробковые пятна и корочки на поверхности кактуса.\n\nЛечение: изолируйте растение, проверьте условия содержания и удалите причину травм или инфекции. При распространении примените фунгицид.\n\nПрофилактика: яркий рассеянный свет, сухая поверхность стебля и аккуратный полив.', 'resource://issue_cactus_scab'),
                ('disease', 'Эдема листьев', E'Признаки: пузырьки и пробковые наросты на нижней стороне листьев из-за избытка воды.\n\nЛечение: сократите полив, увеличьте освещение и вентиляцию. Повреждённые участки не восстановятся.\n\nПрофилактика: не поливайте холодный грунт вечером и не допускайте постоянной сырости.', 'resource://issue_edema'),
                ('disease', 'Хлороз', E'Признаки: пожелтение листовой пластины при сохранении зелёных жилок, слабый рост.\n\nЛечение: проверьте кислотность грунта и корни, внесите подходящее комплексное удобрение с микроэлементами.\n\nПрофилактика: используйте подходящую воду, грунт и соблюдайте дозировку удобрений.', 'resource://issue_chlorosis')
            ) as v(category_code, name, treatment, image_path) on v.category_code = c.code
            on conflict (category_id, name) do update
            set treatment_description = excluded.treatment_description,
                image_path = excluded.image_path;

            delete from app_reference_item_plant_types m
            using app_reference_items i
            where m.reference_item_id = i.id
              and i.name in (
                  'Тля', 'Паутинный клещ', 'Щитовка', 'Мучнистый червец', 'Трипсы', 'Грибные комарики',
                  'Мучнистая роса', 'Корневая гниль', 'Пятнистость листьев', 'Серая гниль',
                  'Ржавчина растений', 'Сажистый грибок', 'Бактериальная мягкая гниль',
                  'Пробковая пятнистость кактусов', 'Эдема листьев', 'Хлороз'
              );

            insert into app_reference_item_plant_types (reference_item_id, plant_type_id)
            select i.id, t.id
            from app_reference_items i
            cross join app_plant_types t
            where
                (i.name in ('Паутинный клещ', 'Мучнистый червец', 'Грибные комарики', 'Корневая гниль', 'Хлороз')) or
                (i.name in ('Тля', 'Трипсы', 'Мучнистая роса', 'Пятнистость листьев', 'Серая гниль',
                            'Ржавчина растений', 'Сажистый грибок', 'Эдема листьев')
                    and t.name in ('Лиственные', 'Цветущие')) or
                (i.name = 'Щитовка' and t.name in ('Лиственные', 'Суккуленты')) or
                (i.name = 'Бактериальная мягкая гниль' and t.name in ('Цветущие', 'Суккуленты')) or
                (i.name = 'Пробковая пятнистость кактусов' and t.name = 'Суккуленты')
            on conflict do nothing;

            drop table if exists app_diseases;
            drop table if exists app_pests;
            """;
        await command.ExecuteNonQueryAsync();
        _initialized = true;
    }

    private async Task<NpgsqlConnection> OpenAsync()
    {
        var connection = new NpgsqlConnection(ServerDatabaseConfig.ConnectionString);
        await connection.OpenAsync();
        return connection;
    }

    private async Task ReadyAsync()
    {
        if (!_initialized)
        {
            await InitializeAsync();
        }
    }

    public async Task<List<User>> GetUsersAsync()
    {
        await ReadyAsync();
        var app_users = new List<User>();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("select id, google_id, name, email, avatar_url, is_admin from app_users order by name", connection);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            app_users.Add(ReadUser(reader));
        }
        return app_users;
    }

    public async Task<User?> GetUserAsync(int id)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("select id, google_id, name, email, avatar_url, is_admin from app_users where id = @id", connection);
        command.Parameters.AddWithValue("id", id);
        await using var reader = await command.ExecuteReaderAsync();
        return await reader.ReadAsync() ? ReadUser(reader) : null;
    }

    public async Task<User?> GetUserByGoogleIdAsync(string googleId)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("select id, google_id, name, email, avatar_url, is_admin from app_users where google_id = @google_id", connection);
        command.Parameters.AddWithValue("google_id", googleId);
        await using var reader = await command.ExecuteReaderAsync();
        return await reader.ReadAsync() ? ReadUser(reader) : null;
    }

    public async Task<int> AddUserAsync(User user)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            insert into app_users (google_id, name, email, avatar_url, is_admin)
            values (@google_id, @name, @email, @avatar_url, @is_admin)
            returning id
            """, connection);
        command.Parameters.AddWithValue("google_id", user.GoogleId);
        command.Parameters.AddWithValue("name", user.Name);
        command.Parameters.AddWithValue("email", user.Email);
        command.Parameters.AddWithValue("avatar_url", user.AvatarUrl);
        command.Parameters.AddWithValue("is_admin", user.IsAdmin);
        user.Id = Convert.ToInt32(await command.ExecuteScalarAsync());
        return user.Id;
    }

    public async Task<int> UpdateUserAsync(User user)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            update app_users set google_id=@google_id, name=@name, email=@email, avatar_url=@avatar_url, is_admin=@is_admin
            where id=@id
            """, connection);
        command.Parameters.AddWithValue("id", user.Id);
        command.Parameters.AddWithValue("google_id", user.GoogleId);
        command.Parameters.AddWithValue("name", user.Name);
        command.Parameters.AddWithValue("email", user.Email);
        command.Parameters.AddWithValue("avatar_url", user.AvatarUrl);
        command.Parameters.AddWithValue("is_admin", user.IsAdmin);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<int> DeleteUserAsync(int id)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("delete from app_users where id=@id", connection);
        command.Parameters.AddWithValue("id", id);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<List<Plant>> GetPlantsAsync()
    {
        await ReadyAsync();
        var app_plants = new List<Plant>();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand(PlantSelectSql + " order by p.name", connection);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            app_plants.Add(ReadPlant(reader));
        }
        return app_plants;
    }

    public async Task<List<Plant>> GetPlantsByUserAsync(int userId)
    {
        await ReadyAsync();
        var app_plants = new List<Plant>();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand(PlantSelectSql + " where p.user_id=@user_id order by p.name", connection);
        command.Parameters.AddWithValue("user_id", userId);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            app_plants.Add(ReadPlant(reader));
        }
        return app_plants;
    }

    public async Task<Plant?> GetPlantAsync(int id)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand(PlantSelectSql + " where p.id=@id", connection);
        command.Parameters.AddWithValue("id", id);
        await using var reader = await command.ExecuteReaderAsync();
        return await reader.ReadAsync() ? ReadPlant(reader) : null;
    }

    public async Task<int> AddPlantAsync(Plant plant)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            insert into app_plants (
                user_id, name, type, plant_type_id, species_id,
                watering_enabled, fertilizer_enabled, lifecycle_phase,
                health_status, location, notes)
            values (
                @user_id, @name, @type,
                (select id from app_plant_types where name=@type), @species_id,
                @watering_enabled, @fertilizer_enabled, @lifecycle_phase,
                @health_status, @location, @notes)
            returning id
            """, connection);
        FillPlant(command, plant);
        plant.Id = Convert.ToInt32(await command.ExecuteScalarAsync());
        return plant.Id;
    }

    public async Task<int> UpdatePlantAsync(Plant plant)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            update app_plants
            set user_id=@user_id,
                name=@name,
                type=@type,
                plant_type_id=(select id from app_plant_types where name=@type),
                species_id=@species_id,
                watering_enabled=@watering_enabled,
                fertilizer_enabled=@fertilizer_enabled,
                lifecycle_phase=@lifecycle_phase,
                health_status=@health_status,
                location=@location,
                notes=@notes
            where id=@id
            """, connection);
        command.Parameters.AddWithValue("id", plant.Id);
        FillPlant(command, plant);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<int> DeletePlantAsync(int id)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("delete from app_plants where id=@id", connection);
        command.Parameters.AddWithValue("id", id);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<List<PlantSpecies>> GetPlantSpeciesAsync(string? plantType = null)
    {
        await ReadyAsync();
        var result = new List<PlantSpecies>();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            select s.id, s.plant_type_id, t.name, s.name, s.latin_name, s.care_description
            from app_plant_species s
            join app_plant_types t on t.id=s.plant_type_id
            where (@plant_type='' or t.name=@plant_type)
            order by t.name, s.name
            """, connection);
        command.Parameters.AddWithValue("plant_type", plantType?.Trim() ?? string.Empty);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            result.Add(new PlantSpecies
            {
                Id = reader.GetInt32(0),
                PlantTypeId = reader.GetInt32(1),
                PlantTypeName = reader.GetString(2),
                Name = reader.GetString(3),
                LatinName = reader.GetString(4),
                CareDescription = reader.GetString(5)
            });
        }
        return result;
    }

    public async Task<int> AddPlantSpeciesAsync(PlantSpecies species)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            insert into app_plant_species (plant_type_id, name, latin_name, care_description)
            values ((select id from app_plant_types where name=@plant_type), @name, @latin_name, @care_description)
            returning id
            """, connection);
        FillSpecies(command, species);
        species.Id = Convert.ToInt32(await command.ExecuteScalarAsync());
        return species.Id;
    }

    public async Task<int> UpdatePlantSpeciesAsync(PlantSpecies species)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            update app_plant_species
            set plant_type_id=(select id from app_plant_types where name=@plant_type),
                name=@name,
                latin_name=@latin_name,
                care_description=@care_description
            where id=@id
            """, connection);
        command.Parameters.AddWithValue("id", species.Id);
        FillSpecies(command, species);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<int> DeletePlantSpeciesAsync(int id)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("delete from app_plant_species where id=@id", connection);
        command.Parameters.AddWithValue("id", id);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<List<WateringSchedule>> GetSchedulesAsync()
    {
        await ReadyAsync();
        var schedules = new List<WateringSchedule>();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            select s.id, s.plant_id, s.start_date, s.period_days, s.notification_time, s.type,
                   s.last_completed_date, s.period_value, coalesce(u.code, 'day')
            from app_watering_schedules s
            left join app_period_units u on u.id = s.period_unit_id
            order by s.start_date
            """, connection);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            schedules.Add(ReadSchedule(reader));
        }
        return schedules;
    }

    public async Task<List<WateringSchedule>> GetSchedulesForPlantAsync(int plantId)
    {
        await ReadyAsync();
        var schedules = new List<WateringSchedule>();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            select s.id, s.plant_id, s.start_date, s.period_days, s.notification_time, s.type,
                   s.last_completed_date, s.period_value, coalesce(u.code, 'day')
            from app_watering_schedules s
            left join app_period_units u on u.id = s.period_unit_id
            where s.plant_id=@plant_id
            """, connection);
        command.Parameters.AddWithValue("plant_id", plantId);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            schedules.Add(ReadSchedule(reader));
        }
        return schedules;
    }

    public async Task<WateringSchedule?> GetScheduleAsync(int plantId, string type)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            select s.id, s.plant_id, s.start_date, s.period_days, s.notification_time, s.type,
                   s.last_completed_date, s.period_value, coalesce(u.code, 'day')
            from app_watering_schedules s
            left join app_period_units u on u.id = s.period_unit_id
            where s.plant_id=@plant_id and s.type=@type
            """, connection);
        command.Parameters.AddWithValue("plant_id", plantId);
        command.Parameters.AddWithValue("type", type);
        await using var reader = await command.ExecuteReaderAsync();
        return await reader.ReadAsync() ? ReadSchedule(reader) : null;
    }

    public async Task<int> AddScheduleAsync(WateringSchedule schedule)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            insert into app_watering_schedules (plant_id, start_date, period_days, period_value, period_unit_id, notification_time, type, last_completed_date)
            values (@plant_id, @start_date, @period_days, @period_value, (select id from app_period_units where code=@period_unit), @notification_time, @type, @last_completed_date)
            returning id
            """, connection);
        FillSchedule(command, schedule);
        schedule.Id = Convert.ToInt32(await command.ExecuteScalarAsync());
        return schedule.Id;
    }

    public async Task<int> UpdateScheduleAsync(WateringSchedule schedule)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            update app_watering_schedules
            set plant_id=@plant_id,
                start_date=@start_date,
                period_days=@period_days,
                period_value=@period_value,
                period_unit_id=(select id from app_period_units where code=@period_unit),
                notification_time=@notification_time,
                type=@type,
                last_completed_date=@last_completed_date
            where id=@id
            """, connection);
        command.Parameters.AddWithValue("id", schedule.Id);
        FillSchedule(command, schedule);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<int> DeleteScheduleAsync(int id)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("delete from app_watering_schedules where id=@id", connection);
        command.Parameters.AddWithValue("id", id);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<CareEvent?> GetCareEventAsync(int scheduleId, DateTime scheduledDate)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            select id, schedule_id, plant_id, scheduled_date, completed_at, status, note
            from app_care_events
            where schedule_id=@schedule_id and scheduled_date=@scheduled_date
            """, connection);
        command.Parameters.AddWithValue("schedule_id", scheduleId);
        command.Parameters.AddWithValue("scheduled_date", scheduledDate.Date);
        await using var reader = await command.ExecuteReaderAsync();
        return await reader.ReadAsync() ? ReadCareEvent(reader) : null;
    }

    public async Task<List<CareEvent>> GetCareEventsAsync(int userId, DateTime from, DateTime to)
    {
        await ReadyAsync();
        var result = new List<CareEvent>();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            select e.id, e.schedule_id, e.plant_id, e.scheduled_date, e.completed_at, e.status, e.note
            from app_care_events e
            join app_plants p on p.id=e.plant_id
            where p.user_id=@user_id and e.scheduled_date between @from and @to
            order by e.scheduled_date
            """, connection);
        command.Parameters.AddWithValue("user_id", userId);
        command.Parameters.AddWithValue("from", from.Date);
        command.Parameters.AddWithValue("to", to.Date);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            result.Add(ReadCareEvent(reader));
        }
        return result;
    }

    public async Task SaveCareEventAsync(CareEvent careEvent)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            insert into app_care_events (
                schedule_id, plant_id, scheduled_date, completed_at, status, note)
            values (
                @schedule_id, @plant_id, @scheduled_date, @completed_at, @status, @note)
            on conflict (schedule_id, scheduled_date) do update
            set completed_at=excluded.completed_at,
                status=excluded.status,
                note=excluded.note
            """, connection);
        command.Parameters.AddWithValue("schedule_id", careEvent.ScheduleId);
        command.Parameters.AddWithValue("plant_id", careEvent.PlantId);
        command.Parameters.AddWithValue("scheduled_date", careEvent.ScheduledDate.Date);
        command.Parameters.AddWithValue("completed_at", careEvent.CompletedAt ?? (object)DBNull.Value);
        command.Parameters.AddWithValue("status", careEvent.Status.ToString());
        command.Parameters.AddWithValue("note", careEvent.Note);
        await command.ExecuteNonQueryAsync();
    }

    public async Task DeleteCareEventAsync(int scheduleId, DateTime scheduledDate)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            delete from app_care_events
            where schedule_id=@schedule_id and scheduled_date=@scheduled_date
            """, connection);
        command.Parameters.AddWithValue("schedule_id", scheduleId);
        command.Parameters.AddWithValue("scheduled_date", scheduledDate.Date);
        await command.ExecuteNonQueryAsync();
    }

    public async Task AddIssueObservationAsync(IssueObservation observation)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            insert into app_issue_observations (plant_id, reference_item_id, observed_at, note)
            values (@plant_id, @reference_item_id, @observed_at, @note)
            returning id
            """, connection);
        command.Parameters.AddWithValue("plant_id", observation.PlantId);
        command.Parameters.AddWithValue("reference_item_id", observation.ReferenceItemId);
        command.Parameters.AddWithValue("observed_at", observation.ObservedAt.Date);
        command.Parameters.AddWithValue("note", observation.Note);
        observation.Id = Convert.ToInt32(await command.ExecuteScalarAsync());
    }

    public async Task<Dictionary<string, decimal>> GetRecommendationSettingsAsync()
    {
        await ReadyAsync();
        var result = new Dictionary<string, decimal>(StringComparer.OrdinalIgnoreCase);
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand(
            "select code, numeric_value from app_recommendation_settings order by code", connection);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            result[reader.GetString(0)] = reader.GetDecimal(1);
        }
        return result;
    }

    public async Task SaveRecommendationSettingAsync(string code, decimal value)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            update app_recommendation_settings
            set numeric_value=@value
            where code=@code
            """, connection);
        command.Parameters.AddWithValue("code", code);
        command.Parameters.AddWithValue("value", value);
        await command.ExecuteNonQueryAsync();
    }

    public async Task<ReportSheet> GetIssueStatisticsReportAsync(int? userId, DateTime from, DateTime to)
    {
        await ReadyAsync();
        var rows = new List<IReadOnlyList<string>>();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            select c.name, i.name, count(*) as occurrence_count,
                   string_agg(distinct p.name, ', ' order by p.name)
            from app_issue_observations o
            join app_plants p on p.id=o.plant_id
            join app_reference_items i on i.id=o.reference_item_id
            join app_reference_categories c on c.id=i.category_id
            where (@user_id is null or p.user_id=@user_id)
              and o.observed_at between @from and @to
            group by c.name, i.name
            order by occurrence_count desc, i.name
            """, connection);
        command.Parameters.Add(
            new NpgsqlParameter("user_id", NpgsqlTypes.NpgsqlDbType.Integer)
            {
                Value = userId ?? (object)DBNull.Value
            });
        command.Parameters.AddWithValue("from", from.Date);
        command.Parameters.AddWithValue("to", to.Date);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            rows.Add([
                reader.GetString(0),
                reader.GetString(1),
                reader.GetInt64(2).ToString(),
                reader.GetString(3)
            ]);
        }
        return new ReportSheet(
            "Вредители и болезни",
            ["Категория", "Название", "Количество", "Растения"],
            rows);
    }

    public async Task<List<Photo>> GetPhotosAsync(int plantId)
    {
        await ReadyAsync();
        var app_photos = new List<Photo>();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("select id, plant_id, title, file_path, date_taken from app_photos where plant_id=@plant_id order by date_taken desc", connection);
        command.Parameters.AddWithValue("plant_id", plantId);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            app_photos.Add(new Photo
            {
                Id = reader.GetInt32(0),
                PlantId = reader.GetInt32(1),
                Title = reader.GetString(2),
                FilePath = reader.GetString(3),
                DateTaken = reader.GetDateTime(4)
            });
        }
        return app_photos;
    }

    public async Task<int> AddPhotoAsync(Photo photo)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            insert into app_photos (plant_id, title, file_path, date_taken)
            values (@plant_id, @title, @file_path, @date_taken)
            returning id
            """, connection);
        command.Parameters.AddWithValue("plant_id", photo.PlantId);
        command.Parameters.AddWithValue("title", photo.Title);
        command.Parameters.AddWithValue("file_path", photo.FilePath);
        command.Parameters.AddWithValue("date_taken", photo.DateTaken);
        photo.Id = Convert.ToInt32(await command.ExecuteScalarAsync());
        return photo.Id;
    }

    public async Task<int> UpdatePhotoAsync(Photo photo)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            update app_photos
            set title=@title, file_path=@file_path, date_taken=@date_taken
            where id=@id
            """, connection);
        command.Parameters.AddWithValue("id", photo.Id);
        command.Parameters.AddWithValue("title", photo.Title);
        command.Parameters.AddWithValue("file_path", photo.FilePath);
        command.Parameters.AddWithValue("date_taken", photo.DateTaken);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<int> DeletePhotoAsync(int id)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("delete from app_photos where id=@id", connection);
        command.Parameters.AddWithValue("id", id);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<List<ProtectionProduct>> GetProtectionProductsAsync()
    {
        await ReadyAsync();
        var products = new List<ProtectionProduct>();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            select id, name, active_ingredient, application_description, hazard_class
            from app_protection_products
            order by name
            """, connection);
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            products.Add(new ProtectionProduct
            {
                Id = reader.GetInt32(0),
                Name = reader.GetString(1),
                ActiveIngredient = reader.GetString(2),
                ApplicationDescription = reader.GetString(3),
                HazardClass = reader.GetString(4)
            });
        }
        return products;
    }

    public async Task<int> AddProtectionProductAsync(ProtectionProduct product)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            insert into app_protection_products (name, active_ingredient, application_description, hazard_class)
            values (@name, @active_ingredient, @application_description, @hazard_class)
            returning id
            """, connection);
        FillProtectionProduct(command, product);
        product.Id = Convert.ToInt32(await command.ExecuteScalarAsync());
        return product.Id;
    }

    public async Task<int> UpdateProtectionProductAsync(ProtectionProduct product)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("""
            update app_protection_products
            set name=@name,
                active_ingredient=@active_ingredient,
                application_description=@application_description,
                hazard_class=@hazard_class
            where id=@id
            """, connection);
        command.Parameters.AddWithValue("id", product.Id);
        FillProtectionProduct(command, product);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<int> DeleteProtectionProductAsync(int id)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("delete from app_protection_products where id=@id", connection);
        command.Parameters.AddWithValue("id", id);
        return await command.ExecuteNonQueryAsync();
    }

    public async Task<List<Pest>> GetPestsAsync(bool? isPest = null, string? plantType = null, string? query = null)
    {
        await ReadyAsync();
        var app_pests = new List<Pest>();
        await using var connection = await OpenAsync();
        var sql = """
            select i.id,
                   i.name,
                   i.treatment_description,
                   i.image_path,
                   c.code = 'pest' as is_pest,
                   coalesce(string_agg(distinct t.name, ', ' order by t.name) filter (where t.name is not null), '') as plant_types
            from app_reference_items i
            join app_reference_categories c on c.id = i.category_id
            left join app_reference_item_plant_types m_all on m_all.reference_item_id = i.id
            left join app_plant_types t on t.id = m_all.plant_type_id
            where (@category_code = '' or c.code = @category_code)
              and (@query = '' or i.name ilike @query_like or i.treatment_description ilike @query_like)
              and (
                    @plant_type = ''
                    or not exists (
                        select 1
                        from app_reference_item_plant_types m
                        where m.reference_item_id = i.id
                    )
                    or exists (
                        select 1
                        from app_reference_item_plant_types m
                        join app_plant_types t on t.id = m.plant_type_id
                        where m.reference_item_id = i.id and t.name = @plant_type
                    )
                  )
            group by i.id, i.name, i.treatment_description, i.image_path, c.code
            order by i.name
            """;
        await using var command = new NpgsqlCommand(sql, connection);
        command.Parameters.AddWithValue("category_code", isPest is null ? string.Empty : isPest.Value ? "pest" : "disease");
        command.Parameters.AddWithValue("plant_type", plantType ?? string.Empty);
        command.Parameters.AddWithValue("query", query?.Trim() ?? string.Empty);
        command.Parameters.AddWithValue("query_like", $"%{query?.Trim() ?? string.Empty}%");
        await using var reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            app_pests.Add(ReadPest(reader));
        }
        return app_pests;
    }

    public Task<List<Pest>> GetPestsAsync() => GetPestsAsync(true);

    public Task<List<Pest>> GetDiseasesFromPestTableAsync() => GetPestsAsync(false);

    public Task<List<Pest>> GetAllPestRecordsAsync() => GetPestsAsync(null);

    public async Task<int> AddPestAsync(Pest pest)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var transaction = await connection.BeginTransactionAsync();
        await using var command = new NpgsqlCommand("""
            insert into app_reference_items (category_id, name, treatment_description, image_path)
            values ((select id from app_reference_categories where code=@category_code), @name, @treatment_description, @image_path)
            returning id
            """, connection, transaction);
        FillPest(command, pest);
        pest.Id = Convert.ToInt32(await command.ExecuteScalarAsync());
        await SavePestPlantTypesAsync(connection, transaction, pest.Id, pest.PlantTypes);
        await transaction.CommitAsync();
        return pest.Id;
    }

    public async Task<int> UpdatePestAsync(Pest pest)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var transaction = await connection.BeginTransactionAsync();
        await using var command = new NpgsqlCommand("""
            update app_reference_items
            set category_id=(select id from app_reference_categories where code=@category_code),
                name=@name,
                treatment_description=@treatment_description,
                image_path=@image_path
            where id=@id
            """, connection, transaction);
        command.Parameters.AddWithValue("id", pest.Id);
        FillPest(command, pest);
        var affected = await command.ExecuteNonQueryAsync();
        await SavePestPlantTypesAsync(connection, transaction, pest.Id, pest.PlantTypes);
        await transaction.CommitAsync();
        return affected;
    }

    public async Task<int> DeletePestAsync(int id)
    {
        await ReadyAsync();
        await using var connection = await OpenAsync();
        await using var command = new NpgsqlCommand("delete from app_reference_items where id=@id", connection);
        command.Parameters.AddWithValue("id", id);
        return await command.ExecuteNonQueryAsync();
    }

    private static User ReadUser(NpgsqlDataReader reader) => new()
    {
        Id = reader.GetInt32(0),
        GoogleId = reader.GetString(1),
        Name = reader.GetString(2),
        Email = reader.GetString(3),
        AvatarUrl = reader.GetString(4),
        IsAdmin = reader.GetBoolean(5)
    };

    private static Plant ReadPlant(NpgsqlDataReader reader) => new()
    {
        Id = reader.GetInt32(0),
        UserId = reader.GetInt32(1),
        Name = reader.GetString(2),
        Type = reader.GetString(3),
        WateringEnabled = reader.GetBoolean(4),
        FertilizerEnabled = reader.GetBoolean(5),
        SpeciesId = reader.IsDBNull(6) ? null : reader.GetInt32(6),
        LatinName = reader.GetString(7),
        LifecyclePhase = reader.GetString(8),
        HealthStatus = reader.GetString(9),
        Location = reader.GetString(10),
        Notes = reader.GetString(11)
    };

    private static CareEvent ReadCareEvent(NpgsqlDataReader reader) => new()
    {
        Id = reader.GetInt32(0),
        ScheduleId = reader.GetInt32(1),
        PlantId = reader.GetInt32(2),
        ScheduledDate = reader.GetDateTime(3),
        CompletedAt = reader.IsDBNull(4) ? null : reader.GetDateTime(4),
        Status = Enum.TryParse<CareTaskStatus>(reader.GetString(5), out var status)
            ? status
            : CareTaskStatus.Planned,
        Note = reader.GetString(6)
    };

    private static WateringSchedule ReadSchedule(NpgsqlDataReader reader) => new()
    {
        Id = reader.GetInt32(0),
        PlantId = reader.GetInt32(1),
        StartDate = reader.GetDateTime(2),
        PeriodDays = reader.GetInt32(3),
        NotificationTime = reader.GetTimeSpan(4),
        Type = reader.GetString(5),
        LastCompletedDate = reader.IsDBNull(6) ? null : reader.GetDateTime(6),
        PeriodValue = reader.IsDBNull(7) ? reader.GetInt32(3) : reader.GetInt32(7),
        PeriodUnit = reader.IsDBNull(8) ? "day" : reader.GetString(8)
    };

    private static Pest ReadPest(NpgsqlDataReader reader) => new()
    {
        Id = reader.GetInt32(0),
        Name = reader.GetString(1),
        TreatmentDescription = reader.GetString(2),
        ImagePath = reader.GetString(3),
        IsPest = reader.GetBoolean(4)
        ,
        PlantTypes = reader.IsDBNull(5)
            ? []
            : reader.GetString(5)
                .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
                .ToList()
    };

    private static async Task SavePestPlantTypesAsync(NpgsqlConnection connection, NpgsqlTransaction transaction, int referenceItemId, IEnumerable<string> plantTypes)
    {
        await using (var delete = new NpgsqlCommand("delete from app_reference_item_plant_types where reference_item_id=@id", connection, transaction))
        {
            delete.Parameters.AddWithValue("id", referenceItemId);
            await delete.ExecuteNonQueryAsync();
        }

        var selected = plantTypes
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(NormalizePlantType)
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Distinct()
            .ToList();

        foreach (var plantType in selected)
        {
            await using var insert = new NpgsqlCommand("""
                insert into app_reference_item_plant_types (reference_item_id, plant_type_id)
                select @id, id
                from app_plant_types
                where name=@plant_type
                on conflict do nothing
                """, connection, transaction);
            insert.Parameters.AddWithValue("id", referenceItemId);
            insert.Parameters.AddWithValue("plant_type", plantType);
            await insert.ExecuteNonQueryAsync();
        }
    }

    private static void FillProtectionProduct(NpgsqlCommand command, ProtectionProduct product)
    {
        command.Parameters.AddWithValue("name", product.Name);
        command.Parameters.AddWithValue("active_ingredient", product.ActiveIngredient);
        command.Parameters.AddWithValue("application_description", product.ApplicationDescription);
        command.Parameters.AddWithValue("hazard_class", product.HazardClass);
    }

    private static string NormalizePlantType(string value)
    {
        var text = value.Trim();
        return text switch
        {
            "Кактусы" => "Суккуленты",
            "Кактусы и суккуленты" => "Суккуленты",
            "Суккулент" => "Суккуленты",
            "Листвен" => "Лиственные",
            _ => text
        };
    }

    private static void FillSchedule(NpgsqlCommand command, WateringSchedule schedule)
    {
        command.Parameters.AddWithValue("plant_id", schedule.PlantId);
        command.Parameters.AddWithValue("start_date", schedule.StartDate.Date);
        command.Parameters.AddWithValue("period_days", schedule.PeriodDays);
        command.Parameters.AddWithValue("period_value", schedule.PeriodValue);
        command.Parameters.AddWithValue("period_unit", schedule.PeriodUnit);
        command.Parameters.AddWithValue("notification_time", schedule.NotificationTime);
        command.Parameters.AddWithValue("type", schedule.Type);
        command.Parameters.AddWithValue("last_completed_date", schedule.LastCompletedDate?.Date ?? (object)DBNull.Value);
    }

    private static void FillPlant(NpgsqlCommand command, Plant plant)
    {
        command.Parameters.AddWithValue("user_id", plant.UserId);
        command.Parameters.AddWithValue("name", plant.Name);
        command.Parameters.AddWithValue("type", plant.Type);
        command.Parameters.AddWithValue("species_id", plant.SpeciesId ?? (object)DBNull.Value);
        command.Parameters.AddWithValue("watering_enabled", plant.WateringEnabled);
        command.Parameters.AddWithValue("fertilizer_enabled", plant.FertilizerEnabled);
        command.Parameters.AddWithValue("lifecycle_phase", plant.LifecyclePhase);
        command.Parameters.AddWithValue("health_status", plant.HealthStatus);
        command.Parameters.AddWithValue("location", plant.Location);
        command.Parameters.AddWithValue("notes", plant.Notes);
    }

    private static void FillSpecies(NpgsqlCommand command, PlantSpecies species)
    {
        command.Parameters.AddWithValue("plant_type", species.PlantTypeName);
        command.Parameters.AddWithValue("name", species.Name);
        command.Parameters.AddWithValue("latin_name", species.LatinName);
        command.Parameters.AddWithValue("care_description", species.CareDescription);
    }

    private static void FillPest(NpgsqlCommand command, Pest pest)
    {
        command.Parameters.AddWithValue("name", pest.Name);
        command.Parameters.AddWithValue("treatment_description", pest.TreatmentDescription);
        command.Parameters.AddWithValue("image_path", pest.ImagePath);
        command.Parameters.AddWithValue("category_code", pest.IsPest ? "pest" : "disease");
    }
}

